### ISSUE TITLE
Are the ip ranged still up to date? 

### ISSUE THREAD

**Issue by LennyPenny** [harrymilnes/Counterstrike-GO-Matchmaking#1]
I think the ip ranges in the repo differ from this [https://github.com/denniskupec/csgo-matchmaking-ip-ranges](url)

**Comment by harrymilnes** [comment]
Unfortunately not, I did have plans to update the project and add an API that would allow the app to stay up to date. Sadly, I didn't get around to it.

As you say, the current IP ranges are available in the GitHub repository you've provided. I'd hope that my code is fairly self explanatory for anyone that wants to add the valid IP ranges.
